apiVersion: v1
kind: Pod
metadata:
  name: test-k8s-elector
spec:
  serviceAccountName: customer-alerting-api-server
  containers:
    - name: leader-elector
      image: 651011001782.dkr.ecr.us-west-2.amazonaws.com/staging/k8s-elector:development-583cac5
      args:
        - "-election=customer-alerting-api-server"
        - "-lock-type=configmaps"
        - "-http=0.0.0.0:4040"
        - "-namespace=customer-alerting"
      ports:
        - containerPort: 4040

